### PR TITLE
Fix: Added DB cleanup and disconnect users who are timed out

### LINKED ISSUE #474: Giving timeout role does not disconnect user from a channel
Currently, when a user is timed out while he is in a channel he can still talk, can't stream or open video but still show off his ugly voice

### PR DESCRIPTION
**Pull request by hasanlatch007**
In case the bot was down and a user was forgiven this should clean it up on ready, so they dont get the the role assigned to them when they rejoin the server.
!closes #474

### CODE REVIEW

File: src/programs/timeout-evasion.ts [hunk 1]
```diff
@@ -100,3 +104,21 @@ class ReportUserOnJoin implements CommandHandler<DiscordEvent.MEMBER_JOIN> {
     );
   }
 }
+
+@Command({
+  event: DiscordEvent.READY,
+})
+class ClearDBOnStart implements CommandHandler<DiscordEvent.READY> {
+  async handle(bot: Client): Promise<void> {
+    const TimedOutUsersId = await prisma.timedOutUsers.findMany();
```
Comment (geisterfurz007) [inline src/programs/timeout-evasion.ts:113]:
```suggestion
    const timedOutUserIds = await prisma.timedOutUsers.findMany();
```

**Review by geisterfurz007 — CHANGES_REQUESTED** [review]

**Review by geisterfurz007 — APPROVED** [review]
